# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
#stages:
#- test
#sast:
 # stage: test
#include:
#- template: Security/SAST.gitlab-ci.yml
default:
  image: docker:27.4.1

  services:
    - name: docker:27.4.1-dind
      alias: docker

  before_script:
    - echo "Login to Docker registry"
    - ping -c 4 deb.debian.org
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $REGISTRY

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
      when: always
    - when: never

variables:
    DOCKER_DRIVER: overlay2
    REGISTRY: registry.git.fh-aachen.de
    #BUILD_RUNNER_TAG: build
    #PUSH_RUNNER_TAG: build
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
    GITLAB_RUNNER_SERVICE_START_TIMEOUT: "600"

stages:
  - build
  #- push

.build_image:
  stage: build
  script:
    - docker info --format '{{.ServerVersion}}' || echo "Docker daemon not running"
   # - docker logs $(docker ps -q -f name=docker) || echo "No Docker service logs available"
    - docker build -t $CI_REGISTRY_IMAGE/$IMAGE_NAME:$CI_COMMIT_REF_NAME .
    - docker images
    - docker push $CI_REGISTRY_IMAGE/$IMAGE_NAME:$CI_COMMIT_REF_NAME

  rules:
    - changes:
        - Dockerfile
        - src/**/*
  

  

build_chatbot:
  extends: .build_image
  variables:
    IMAGE_NAME: centralApp-ci



