# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
#stages:
#- test
#sast:
 # stage: test
#include:
#- template: Security/SAST.gitlab-ci.yml
stages:
  - build

variables:
  APP_ENV: production
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  COMPOSER_ALLOW_SUPERUSER: 1

services:
  - name: docker:dind
    alias: docker

before_script:
  - echo "Login to Docker registry"
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $REGISTRY
  - apk add --no-cache docker-cli
  - echo " Setting up GitLab CI"

build:
  stage: build
  script:
    - echo "Building Docker image..."
    - docker build -t registry.gitlab.com/$CI_PROJECT_PATH/central-app:$CI_COMMIT_SHORT_SHA .
    - docker push registry.gitlab.com/$CI_PROJECT_PATH/central-app:$CI_COMMIT_SHORT_SHA
  only:
    - main


